[package]
name = "tui-2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tui = "0.16.0"
termion = "1.5.6"
rand = "0.8.0"